# Generated by Django 3.1.13 on 2023-05-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20230505_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='car',
            name='miles',
        ),
    ]
