# Generated by Django 3.1.13 on 2023-05-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20230505_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='passengers',
        ),
    ]
