# Generated by Django 3.1.13 on 2023-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='interior',
        ),
    ]
