# Generated by Django 3.1.13 on 2023-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_interior'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='interior',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_no',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
